# Generated by Django 2.2.5 on 2019-10-04 15:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=32, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Restaurants')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItems'),
        ),
    ]
